/**
 * @class LabelsTitles
 * This file holds all the Labels and Titles to be used throughout the application for the purpose of Internatio.
 * @singleton
 */
Ext.define('Goals.util.LabelsTitles', {
    singleton: true,

    alternateClassName: ['LabelsTitles'],
    //Put the labels here
    SNO: 'Sl.No',
    NAME: 'Name',
    ROLES: 'Roles',
    ABOUT: "About",
    SKILLS: 'Skills',
    MONTH: 'Month',
    JOININGDATE:'Joining Date',
    TODONAME: 'ToDo List',
    SUPERVISOR: 'Supervisor',
    DESIGNATION: 'Designation',
    EMPLOYEECODE: 'Emp Code',
    nominateTitle: 'Nominate',
    JOININGDATE: 'Joining Date',
    TECHNOLOGIES: 'Technologies',
    DAYSONBENCH: 'Days On Bench',
    OTHERSKILLS: "Additional Skills : ",
    AVAILABLEFROM: 'Available From',
    PRIMARYSKILL: "Primary Skill : ",
    CURRENTPROJECT: 'Current Project',
    PROJECTNAME: 'Project Name',
    EXPERIENCELEVEL: 'Experience Level',
    POTENTIALPROJECT: 'Potential Project',
    EMPLOYMENTSTATUS: 'Employment Status',
    AVAILABILITYSHEET: 'Availability Sheet',
    PREFERREDLOCATION: 'Preferred Location',
    SKILLSCOLUMNCHART: 'Skills Column Chart',
    AVAILABILITYCHARTS: 'Availability Charts',
    YEARSINWTC: 'Years in current organization',
    RESOURCEAVAILIBILITY1: 'Resource Availibility',
    CALCULATEDCOLUMNCHART: 'Calculated Column Chart',
    FINANCIALYEAR: 'Financial Year',
    SKILL : 'Skills',
    EXPERIENCE : 'Experience',
    BILLABLE : 'Is Billable',
    RESOURCEAVAILIBILITY: '<b>RESOURCE AVAILIBILITY</b>',
    EMPLOYEEID: 'Employee Id',
    EMPLOYEENAME: 'Employee Name',
    ALLOCATIONFACTOR: 'Allocation Factor',
    PRIMARYSKILL :'Primary Skill',
    CAROUSELTEXT:[
        'Track the Karma Score of Employee',
        'Know How much Employees are Engaged',
        'Timely & Accurate Feedback form Employees',
        'Karma at Workplace'
    ],
    AFTEROTPVALIDATION:'OTP Validated Succesfully.<br>Please Continue with Login.',
    EMPLOYEEREPORT :{
        EMPID : 'Emp Id',
        EMPLOYEENAME :'EmployeeName',
        DESIGNATION :'designation',
        PRIMARYSKILLS:'primaryskills',
        EMAIL :'Email',
        PHONENUMBER:'PhoneNumber',
        REPORTINGTO:'ReportingTo',
        EMPSTATUS:'Status', 
        EMPSKILLS: "Technologies",
        EMPEXPERIENCE:'Experience',
        BILLABLE: 'Is Billable'
        },
    KARMADASHBOARDSCORE:{
        TITLE: '<b style = "color:#fff">Karma Dashboard</b><span style="color:#fff; float: right">Total Score: {totaActualKarma}/{totalPotentialKarma}</span>',
        CATEGORY: 'Category',
        PERIOD: 'Period',
        ACTUALMONTH: 'Actual Per Month',
        AMTOOLTIP: 'Actual Karma Per Month',
        POTENTIALMONTH: 'Potential Karma Per Month',
        APPROVEDBY: 'Approved By',

        ACCEPTED: 'Accepted',
        PENDING: 'Pending',
        REJECTED: 'Rejected',
        KARMACATEGORY: 'Karma Category',
        KARMANAME: 'Karma Name',
        MONTH: 'Month & Year',
        POINT: 'Points',
        ACTUALPOINT: 'Actual Point',
        ALTEREDPOINTS: 'Altered Points',
        REASON : 'Reason',
        ACTIONS: 'Actions'
    },
    // PRIMARYSKILL: 'Primary Skill',
    //Settings block
    GOAL_SETTINGS: 'Goal Settings',
    FINANCIAL_YEAR_SETTINGS: 'Financial year settings',
    NOMINATION: {
        SELFNOMINATE: 'Self Nominate',
        SENTBACKNOMINATION: 'Nominate Collegues',
        SENDAPPROVAL: 'Submit',
        CATEGORY: 'Category',
        CATEGORYEMPTYTEXT: 'Pick a Category',
        MONTH: 'Select Month & Yesr',
        SELECTEMPTYTEXT: 'Select',
        KARMA: 'Choose the type of Karma',
        SELECTFREQUENCY: 'Select Frequency',
        ACHIEVEMENT: 'Enter no of Tasks done ',
        ACHIEVEMENTEMPTYTEXT: 'Achievements',
        BLANKTEXT: 'Value should be 1 or more!',
        COLUMNCATEGORYNAME: 'Karma Category ',
        COLUMNKARMANAME: 'Karma Name',
        COLUMNFREQUENCY: 'Frequency',
        COLUMNKARMAPOINTS: 'Karma Points',
        COLUMNMONTH: 'Month & Year',
        COLUMNCOMMENT: 'Comments',
        COLUMNACTION: 'Actions',
        NOMINATEOTHERTITLE: 'Nominate',
        SEARCHPEOPLETEXT: 'Search People',
        SELECTDATETEXT: 'Select Date',
        SELECTKARMATEXT: 'Karma',
        KARMAUNITSTEXT: 'Karma Units',
        NOMINATEOTHERSUBMIT: 'Submit',
        CONFIRMTITLE: 'Confirmation'
    },
    ROLE: {
        ROLE: 'Role',
        APPLY: 'Apply',
        VIEWNAME: 'View Name',
        ALLOW: 'Allow',
        SEARCHROLE: 'Search View Name'

    },
    SHEETS: {
        SELECTMONTH: 'Select Month',
        SELECTYEAR: 'Select Year',
        APPLY: 'Apply',
        RESET: 'Reset',
        EMPLOYEEBENCH: 'Employees on bench',
        AVAILABILITYSHEET: 'Availability Sheet',
        DOWNLOADEXCEL: 'Download as excel',
        BENCHSHEETNAME: 'EmployeesOnBenchSheet',
        BENCHSHEETTITLE: 'Employees on Bench Sheet',
        AVAILABILITYSHEETNAME: 'AvailabilitySheet',
        ALLOCATIONSHEET: 'Allocation Sheet',
        AVAILABILITYSHEETTITLE: 'Availability Sheet',
        BLOBTYPE: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        BENCHFACTOR: 'Bench Factor'
    },
    EMPLOYEERESIGNATION: {
        PROPOSEDDATE: 'Proposed Relieving Date',
        REMARKS: 'Remarks',
        ACTUALDATE: 'Actual Relieving Date',
        FINALREMARKS: 'Final Remarks',
        NAME: 'Name',
        PROJECT: 'Project',
        STARTDATE: 'Start Date',
        ENDDATE: 'End Date'
    },
    EMPSETUP: {
        ROLES: '<h3>Role</h3>',
        NAME: 'Name',
        DESCRIPTION: 'Description',
        BTNCANCEL: 'Cancel',
        SAVE: 'Save',
        DEPARTMENT: {
            NAME: 'Name',
            DESCRIPTION: 'Description',
            ADDNEW: 'Add New',
            WINDOWTITLE: 'Department',
            CANCEL: 'Cancel',
            SAVE: 'Save',
            DEPNAME: '<h3>Department</h3>'
        },
        DESIGNATION: {
            NAME: 'Name',
            DESCRIPTION: 'Description',
            ACRONYM: 'Acronym',
            RESPONSIBILITIES: 'Responsibilities',
            WINDOWTITLE: 'Designation',
            ROLESANDRESPONSIBILITIES: 'Roles and Reaponsibilities',
            CANCEL: 'Cancel',
            SAVE: 'Save',
            DNAME: '<h3>Designation</h3>'


        },
        ACCOUNT: {
            ACCOUNT: 'Account',
            UPDATE: 'Update',
            NAME: 'Name',
            CMPNAME: 'Name of the company',
            REGPHONENO: 'Enter Valid phone number ex: 9848012345',
            EMAIL: 'Email',
            OVERVIEW: 'Overview',
            OVERVIEWPLACEHOLDER: 'Short description about company',
            ADDRESS: 'Address',
            PHONENO: 'Phone Number',
            COUNTRY: 'Country',
            STATE: 'State',
            CITY: 'City',
            POSTALCODE: 'Postal Code',
            UPDATE: 'Update',
            RESET: 'Reset',
            ALTMSG: 'App View Logo',
            MANDATORYFIELD : '<span style="color:red;font-weight:bold" data-qtip="Required">*</span>'
        },
        ROLE: {
            ROLES: '<h3>Role</h3>',
            NAME: 'Name',
            DESCRIPTION: 'Description',
            BTNCANCEL: 'Cancel',
            SAVE: 'Save'
        },
        FINANCIALYEAR: {
            FTITLE: 'Financial Year',
            FYEAR: '<h3>Financial Year</h3>',
            NAME: 'Name',
            SEARCH: 'Search...',
            STARTDATE: 'Start Date',
            ENDDATE: 'End Date',
            DELETE: 'Delete',
            ADDBTN: 'Add New',
            CANCEL: 'Cancel',
            SAVE: 'Save',
        },
        EMPTAB: {
            REPORTINGWIN : {
                TITLE : 'Please provide reason to change the reporting manager',
                COMMENT: 'Please provide the comment',
                OK: 'ok',
                CANCEL: 'Cancel',
                RESALERT: 'Result not found'
            },
            EMP: {
                SEARCHTEXT: 'Search By Name...',
                ADDNEWBTN: 'Add New',
                FIRSTNAME: 'First Name',
                LASTNAME: 'Last Name',
                EMAIL: 'Email',
                DEPARTMENT: 'Department',
                PRIMARYSKILL: 'Primary Skill',
                DESIGNATION: 'Designation',
                REPORTINGTO: 'Reporting To',
                JOININGDATE: 'Joined Date',
                CONFIRMEDDATE: 'Confirmed Date',
                SEPARATEDDATE: 'Separated Date',
                DEPARTMNT: 'Department',
                REPORTTO: 'Reporting To',
                NOTICEDATE: 'Notice Date',
                EMPSTATUS: 'Employee Status',
                PANNUMBER: 'PAN Number',
                ADDRESS: 'Address',
                CITY: 'City',
                STATE: 'State',
                COUNTRY: 'Country',
                GREYHRID: 'GreytHR Id',
                CANCELBTN: 'Cancel',
                SAVEBTN: 'Save',
                MULTICHECKBOX: 'Select one or more check boxes',
                PERSONALDETAILS: 'Personal Details',
                PESONALCANCELBTN: 'Cancel',
                PERSONALSAVEBTN: 'Save',
                DOB: 'Date Of Birth',
                DATEEMPTYTEXT: 'DD-MM-YYYY',
                GENDER: 'Gender',
                MALE: 'Male',
                FEMALE: 'Female',
                MARITALSTATUS: 'Marital Status',
                ANNIVERSARYDATE: 'Anniversary Date',
                PHONEEMPTY: 'Enter phone number',
                PHONEREGEX: 'Enter Valid phone number ex: 9848012345',
                PHONELABEL: 'Phone number',
                BLOODGROUP: 'Blood Group',
                PANNO: 'Pan No',
                ADHAARNO: 'Aadhar No',
                EMERGENCYPHN: 'Emergency Number',
                COMMADDRESSES: 'Communication Address',
                PERMADDRESS: 'Permanent Address',
                EMPFORM: {
                    TITLE: 'Employee',
                    CANCELBTN: 'Cancel',
                    SAVEBTN: 'Save',
                    FIRSTNAME: 'First Name',
                    MIDDLENAME: 'Middle Name',
                    LASTNAME: 'Last Name',
                    EMAIL: 'Email',
                    EMPCODE: 'Employee Code',
                    MANDATORYFIELD : '<span style="color:#E84949;" data-qtip="Required">*</span>'
                },
                WORKFORM: {
                    TITLE: 'Work Details',
                    CANCEL: 'Cancel',
                    SAVECONTINUE: 'Save & Continue',
                    REPORTINGTO: 'Reporting To',
                    DESIGNATION: 'Designation',
                    DEPARTMENT: 'Department',
                    PSKILL: 'Primary Skill',
                    STATUS: 'Status',
                    JOBTYPE: 'Job Type',
                    JDATE: 'Joining Date',
                    CDATE: 'Confirm Date',
                    SDATE: 'Separated Date',
                    NDATE: 'Notice Date',
                    GREYHR: 'GreytHR Id'
                },
                ADDRESSFORM: {
                    TITLE: 'Address',
                    CANCEL: 'Cancel',
                    SAVE: 'Save',
                    CADDRESS: 'Current Address',
                    DETAILS: 'Details',
                    COUNTRY: 'Country',
                    STATE: 'State',
                    CITY: 'City',
                    ZIP: 'Zip Code',
                    PADDRESS: 'Permanent Address',
                    CHECKADDRESS: 'Check if CurrentAddress and PermanentAddress are same.',
                },
                ACCESSFORM: {
                    ROLE: 'Role',
                    TITLE: 'Access Details',
                    SAVE: 'Save',
                    CANCEL: 'Cancel'
                }
            },
            REPORTS: {
                STATUS: 'Status',
                DATERANGE: 'Date Range',
                GREYTHRID: 'Greythr Id',
                APPLY: 'Apply',
                CLEAR: 'Clear',
                FIRSTNAME: 'First Name',
                LASTNAME: 'Last Name',
                EMAIL: 'Email',
                DEPARTMENT: 'Department',
                DESIGNATION: 'Designation',
                REPORTINGTO: 'Reporting To',
                JOINEDDATE: 'Joined Date',
                CONFIRMEDDATE: 'Confirmed Date',
                SEPARATEDDATE: 'Separated Date',
                EMPLOYEESTATUS: 'Employee Status',
                ADHAARNO: 'Aadhar No',
                EXCELDOWNLOAD : 'Download as excel'
            },
            UTILIZATION: {
                EMPTYTEXT: 'Filter By',
                NAME: 'Employee Name',
                EMPID: 'Employee ID ',
                DESIGNATION: 'Designation',
                EMAILID: 'Email ID',
                STARTDATE: 'Start Date',
                ENDDATE: 'End Date',
                ALLOCATION: 'Allocation %',
                DWLDEXCEL: 'Download as excel',
                PRIMARY:'Primary Skill',
                PROJECTROLE: 'Project Role',
                SUPERVISOR: 'Supervisor Name',
                PROJECTNAME: 'Project Name',
               
            }
        }
    },
    RESOURCEREQUEST: {
        NEWALLOCATION: 'NEW ALLOCATION',
        UPDATEALLOCATION: 'UPDATE ALLOCATION',
        EMPTYSEARCH : 'Search Project',
        EMPLOYEE: 'Employee',
        STARTDATE: 'Start Date',
        ENDDATE: 'End Date',
        ROLE: 'Role',
        ALLOCATIONPERCENT: 'Allocation Percent',
        SHADOWRESOURCE: 'Shadow Resource',
        ACTIONCOLUMN: 'Action Column',
        SAVE: 'Save',
        RESET: 'Reset',
        UPDATE: 'Update',
        RESOURCE: 'Resource',
        STARTTOOLTIP : 'startdate',
        ENDTOOLTIP : 'enddate',
        ROLETOOLTIP : 'role',
        ALLOCATIONTOOLTIP :'allocation percent',
        SHADOWTOOLTIP:'shadow resource',
        EDITTOOLTIP : 'Edit Record',
        DELETETOOLTIP : 'Delete Record'
    },
    MoM : {
        EMPTYTEXTAGENDA : 'Search for agenda',
        CREATEMOM: 'Create MOM',
        DRAFTS : 'Drafts',
        TITLE :'Title',
        STARTDATE : 'Start Date: ',
        DATEEMPTY : 'DD-MM-YYYY',
        STARTTIME : 'Start Time: ',
        TIMEEMPTY : 'HH-MM',
        ENDTIME : 'End Time: ',
        DURATION : 'Duration: ',
        HRS : 'Hrs',
        DESCRIPTION : 'Description',
        SNO : 'Sno',
        ACTIONITEM : 'Action Item / Task Details',
        ASSIGNEDTO : 'Assigned To',
        DUEDATE : 'Due Date',
        STATUS : 'Status',
        PARTICIPANTS : 'Participants',
        EMPTYTEXTDATA : '<div class="projects-emptytext-cls">No Data Found</div>'
    },
    EXECUTIVEDASHBOARD: {
        RESOURCEAPPROVAL: {
            NAME: 'Employee Name',
            EMPREQ: 'Requested Employee',
            ALLOCATIONPER: 'Allocation percent',
            PROJECT: 'Project',
            FORMDATE: 'From Date',
            TODATE: 'To date',
            APPROVE: 'Approve',
            ACCEPT: 'Accept',
            REJECT: 'Reject',
            NODATAFOUND: ' <div class="ddo-emptytext" >No data found</div>',
            REASON: 'Reason:',
            SUBMIT: 'Submit',
            EMPTYTEXT: 'Please enter reason for rejecting..',
            WITHOUTREASON:  'Approve without comments',
        },
        HR:{
            EMPTYTEXT: '<div class="ddo-emptytext" >No data found</div>',
            FORM: 'From',
            SUBMITEDDATE:'Submited date',
            KARMAUNITS:'Karma Units',
            DERIVEDPOINTS :'Derived Points',
            TO: 'To',
            KARMAPOINTS: 'Points',
            KARMACAT: 'Category',
            KARMA: 'Name',
            MONATH: 'Month',
            COMMENTS: 'Comments',
            SUBMIT : 'Submit',
            KARMAREVIEW:'Karma Review',
            HRREVIEWPOINTS:'Hr Review Points',
            USERCOMMENTS:'User Comments'
        },
        FINANCE:{
            EMPTYTEXT: '<div class="ddo-emptytext" >No data found</div>',
            FORM: 'From',
            SUBMITEDDATE:'Submited date',
            KARMAUNITS:'Karma Units',
            DERIVEDPOINTS :'Derived Points',
            TO: 'To',
            KARMAPOINTS: 'Points',
            KARMACAT: 'Category',
            KARMA: 'Name',
            MONATH: 'Month',
            COMMENTS: 'Comments',
            SUBMIT : 'Submit',
            KARMAREVIEW:'Karma Review',
            FINANCEREVIEWPOINTS:'Finance Review Points',
            USERCOMMENTS:'User Comments'
        },
        KARMAAPPROVAL: {
            EMPTYTEXT: '<div class="ddo-emptytext" >No data found</div>',
            FORM: 'From',
            TO: 'To',
            KARMAPOINTS: ' Points',
            KARMACAT: 'Karma Category',
            KARMA: 'Karma Name',
            MONATH: 'Month',
            COMMENTS: 'Comments',
            APPROVE: 'Approve',
            ACCEPT: 'Accept',
            REJECT: 'Reject',
            SENDBACK: 'Send Back',
            SENDBACKBTN: 'SendBack',
            WINCOMMENT: 'Comments:',
            REJECTREASON: 'Reason:',
            ACHIEVEMENT: 'Achievement <span style="color: red;">*</span>',
            REASON: 'Reason for rejection <span style="color: red;">*</span>',
            EMPTEXT: 'Type your messsage...',
            SUBMIT: 'Submit',

            

        },
        PROJECT: {
            UPLOADTEXT: 'Upload Image',
            EMPTYSEARCHPROJECT : 'Search for project by name/tech/client',
            PROJECTSTATUS : "Project Status",
            ADDPROJECTS : 'Add Project',
            PROJECTWINDOW : {
                PROJECTTITLE : '<span class="nom-name-cls">Add Project</span>',
                CANCEL: 'Cancel',
                SAVE : 'Save',
                EMPTYPROJECT : 'Project Name',
                EMPTYSEARCH:'Search Key',
                SALESEMPTY : 'Sales representative',
                CLIENTNAME : 'Client Name',
                UPLOADTEXT : 'Upload Max Size:2MB 500*500 px'

            },
            NOTES : {
               STATUSEMPTY : 'Status',
               NOTEEMPTY : 'Type of Note',
               CREATE : 'Create',
               EMPTYDATAFOUND : '<div class="projects-emptytext-cls">No Data Found</div>',
               EMPTYNOTETYPE : 'Note Type',
               XTEXT : 'X',
               EMPTYTITLE : 'Title',
               SUBMIT : 'Submit'
            },
            MOM:{
            EMPTYTEXT: 'Search people/agenda',
            DRAFTS: 'Save as Draft',
            CREATE :'Create MOM',
            TITLE:'Type your Moms title',
            STARTDATE :' Date ',
            DATEEMPTY : 'DD-MM-YYYY',
            STARTTIME : 'Start Time ',
            TIMEEMPTY : 'HH-MM',
            ENDTIME : 'End Time ',
            DURATION : 'Duration',
            HRS : 'Hrs',
            DESCRIPTION : 'Description',
            SNO : 'Sno',
            ACTIONITEM : 'Action Item / Task Details',
            ACTIONITEMEMPTY : 'Add Task Details',
            ASSIGNEDTO : 'Assigned To',
            DUEDATE : 'Due Date',
            STATUS : 'Status',
            PARTICIPANTS : 'Participants',
            EMPTYDATATEXT : '<div class="projects-emptytext-cls">No Data Found</div>',
            ABSENTEES: ' Absentees',
            MOMACTIONTITLE: 'Action Items',
            FOLLOWUP:'Follow Up',
            ACTIONDELETE: 'Deleted',
            COMPLETED: 'Completed',
            STATUS: 'Status',
            ENDDATE:'Due Date',
            MOMSTARTDATE:'Start Date',
            TASK:'Task Details',
            MOMTITLE:'MOM Title',
            MOMAGENDA:'MOM Agenda',
            ASSIGNEDTO:'Assigned To',
            SEARCHBOX : 'Search people/agenda',
            COLUMNS : 'COLUMNS',
            HIDEORUNHIDE : 'Hide Or Unhide Columns',
            AGENDA : 'Agenda',
            APPLY:'Apply'
            },
            TECHNOLOGIES: {
                SEARCH: 'Search Technologies',
                ADDTECHNOLOGIES: 'Add Technologies',
                ADDTECHNOLOGY: 'Add Technologies',
                SEARCHTECHNOLOGY: 'Select Technology',
                TECHNOLOGYNAME: 'Technology Name',
                SELECTVERSION: 'Select Version',
                VERSION: 'Version',
                SUBMITBTN: 'Submit',
                NOTECHNOLOGY: 'No Technologies available',
            },
            PROJECTS: {
                EMPTYTEXT: 'Change Status',
                SEARCHPROJECT:'Search Project',
                FEEDBACK : 'Feedback',
                LABEL:'Switch to project'
            },
            PEOPLE: {
                RESOURCE: 'Past Resources', 
                ADDPEOPLE: 'Add People',
                SEARCHPPL: 'Search people',
                NODATAFOUND: '<div class="projects-emptytext-cls">No Data Found</div>',
                CANCEL: 'Cancel',
                SAVE: 'Save',
                STARTDATE: 'Start Date',
                EMPTYSTARDT: 'YYYY-MM-DD',
                ENDDATE: 'End Date',
                ALLOCATION:'Allocation Percent',
                ROLE: 'Role',
                BOXLABEL: 'Shadow resource',
                CNFMDELETE: 'Confirm People Delete',
            }
        }
    },
    REDEEM: {
        ORDERHISTORY: '<h3>Order History</h3>',
        ORDERBY: 'Ordered By',
        ORDERDATE: 'Order Date',
        ORDERNUMBER: 'Order No',
        POINTS: 'Points',
        ORDERREF: 'Order Refrence',
        STATUS: 'Status',
        NORECORD: 'No records',
        ORDERDETAILS: 'Order details',
        PRODUCTS: 'Products',
        NAME: 'Name',
        QTY: 'Qty',
        COMPLETEORDER: 'Complete&nbsp&nbspOrder',
        CANCELORDER: 'Cancel&nbsp&nbspOrder'
    },
    HELP: {
        HELPTOOLBAR : 'Frequently Asked Questions',
        HELPTITLE: 'DDO-Facts and Features'
    },
    INITIATEEXIT:{
          EMPLOYEE:'Employee',
          REASON:'Reason',
          DOCUMENTUPLOAD:'Document Upload',
          SUBMIT:'Submit'
    },
    EMPLOYEEDASHBOARD: {
        GROUPS:{
            CHOOSEGROUP: 'Choose Group',
            GROUPNAME: 'group_name',
            NEWGROUP: 'Create New Group',
            DELETE: 'Delete',
            ADDPEOPLE: 'Click to add people',
            ADDPPLEMPTYTEXT: '<div class="ddo-group-search-empty">Please add people into the group.</div>', 
            SEARCHEMPTYTEXT: '<div class="ddo-emp-list-empty">No Data Found</div>',
            GROUPSEARCH: '<div class="ddo-group-search-empty">No Data Found</div>',
            ALL: 'All ', 
            SEARCHEMP:'Search employee',
            ADDTOGRP: 'Add to group',
            ADDGRPEMP:'Add Group Employees',
            ADDPPL: 'Add People',
            SRCHROLE: 'Search Role',
            YOURSCORE:'Your Score',
        },
        ORGCHART : {
           EMPNAME : 'Employee Name',
           DEPARTMENT : 'Department',
           RESET : "Reset"
        },
        NOTICE : {
            EMPID : 'Employee Id',
            EMPNAME: 'Employee Name',
            REPORTING : 'Reporting Manager',
            JOININGDATE:'Joining Date',
            EMPSTATUS : 'Employee Status',
            STATUS : 'Status',
            DOCUMENT : 'Document',
            ACTION:'Action',
            PROCEED : 'Proceed',
            BACK:'Back',
            NEXT:'Next',
            REQUEST :'Update Date',
            SUBMIT : 'Submit',
            UPDATE : 'Update',
            EMPLOYEE :'Employee',
            PROJECT : 'Project',
            STARTDATE : 'Start Date',
            ENDDATE :'End Date',
            EDIT : 'Edit',
            APP :'APP',
            CHECKCOLUMN : 'checkcolumn',
            ALLOW : 'Allow',
            PROPOSEDDATE:'Proposed Relieving Date',
            REMARKS:'Remarks',
            ACTUALDATE:'Separated Date',
            FINALREMARKS:'Final Remarks',
            NAME:'Name',
            PROJCT:'Project',
            STARTDATE:'Start Date',
            ENDDATE:'End Date'
        },
        KARMASCORE: {
            DOWNLOAD:'Download',
            GROUPBY:'Group By',
            NODATAFOUNT: '<div class="ddo-adv-karma-search-empty">No Data Found</div>',
            DATARANGE: 'Date Range',
            FILTERS: 'Filters',
            PROJECT:'Projects',
            PRIMARYSKILL:'PrimarySkill',
            DEPARTMENT: 'Department',
            DESIGNATION:'Designation',
            SUPERVISOR: 'Supervisor',
            FORM: 'FROM',
            TO:'TO',
            APPLY:'Apply',
            CANCEL: 'Cancel',
            DTRANGE: 'Date Range',
        },
        KARMASETUP: {
            NOICON: '<div class = "ddo-emptytext">No Icons Added</div>',
            WALLET : {
                SEARCH: 'Search...',
                ADDNEW: 'Add New',
                WALLETOWNER: 'Wallet Owner',
                SEARCHFOR: 'Search for...',
                POINTS: 'Points',
                YEAR: 'Year',
                DESCRIPTION: 'Description',
                SHARABLE: 'Sharable',
                ADDWALLET: 'Add Wallet',
                CANCEL: 'Cancel',
                SAVE: 'Save',
                SELECTWTYPE: 'Select Wallet Type',
                SELECTEMPLOYEE: 'Select Employee',
                POINTS: 'Points',
                YEAR: 'Year' ,
                SHARABLE: 'Sharable'
            },
            KARMARULE : {
                NAME : 'Name',
                SEARCH : 'Search...',
                DESCRIPTION : 'Description',
                SELFNOMINATE : 'Self Nominate',
                RULETYPE : 'Rule Type',
                CANCEL : 'Cancel',
                SAVE : 'Save',
                TITLE : 'Karma Rule'
            },
            KARMACATEGORIES : {
                TITLE : 'Karma Category'
            },
            KARMAACCESS : {
                DELTOOLTIP : 'Delete',
                WINDOWTITLE : 'Add Karma Access',
                CANCEL : 'Cancel',
                SAVE : 'Save',
                KARMALABEL : 'Karma',
                SELECTKARMA : 'Select Karma',
                ROLE : 'Role',
               EMPLOYEE:'Employee',
               KARMA : 'Karma',
               ROLES : 'Roles',
               EMPLOYEES : 'Employees'
            },
            KARMARATING: {
                SAVE: 'Save',
                NOICON: '<div class = "ddo-karmasetup-emptytext">No Icons Added</div>'
            }
        },
    },
    KARMAREPORT:{
        EMPLOYEE:'Employee',
        FROM:'From',
        TO:'To',
        SEARCH:'Search',
        CATEGORY:'Category',
        EMPLOYEENAME:'Employee Name',
        DESIGNATION:'Designation',
        KARMA:'Karma',
        POTENTIALKARMA:'Potential Karma',
        ACTUALKARMA:'Actual Karma',
        NOMINATIONMONTH:'Nomination Month',
        SEARCHEMPLOYEE:'Search Employee',
        CLEARFILTER:'Clear Filter',
        DOWNLOAD:'Download',
        SUPERVISOR:'Supervisor'

    },
    GOALS: {
        EXECUTIVEVIEW : {
            MEASUREMENTCRITERIA : 'Measurement Criteria',
            COMMENT: 'Comments',
            TITLE : 'Execution Plan',
            SHAREWITH: 'Share with',
            UPDATE: 'Update',
            RATING: 'Rating',
            CANCELGOAL: 'Cancel Goal',
            COMPLETE: 'Complete',
            MOVEDRAFT: 'Move to Drafts',
            APPROVAL : 'Approve',
            NOTESTXT: 'Notes',
            ADDICON : '&#x271B',
            NOTES: {
                NOREC: 'No Records Found',
                NOTETYPE: 'Note Type',
                COMMENT: 'Comment',
                DATECREATED: 'Created Date',
                LIPSUM: 'Lorem Ipsum'
            },
            RATINGNOICON: '<div class = "ddo-karmasetup-emptytext">No Icons Added</div>',
            SELECTEMP: 'Select Employee',
            ASSIGNKARMA: 'Assigned Karma :',
            AMAZING: 'Amazing',
            SUPERB: 'Superb',
            GOOD: 'Good',
            ADDNEWTASK: 'Add New Task',
            DEL: 'Delete',
            TASK: 'Task',
            TASKNAME: 'Task Name',
            TARGETDATE: 'Target Date',
            DATE: 'Date',
            DURATION: 'Duration',
            HOURS: 'Hrs',
            GOALNAME: 'Goal Name',
            PARENTGOAL: 'Parent Goal',
            PROGRESS: 'Progress'
        },
        GOALMAIN: {
            SEARCHGOAL: 'Search Goals',
            CFILTER: 'Clear Filters',
            ADDNOTES: 'Add Notes',
            CANCEL: 'Cancel',
            SAVE: 'Save',
            DETAILS: 'Details',
            DATE: 'Date : ',
            DATEEMPTYTEXT: 'YYYY-MM-DD',
            GOALNAME: 'Goal Name',
            SEARCHPEOPLE: 'Search People',
            DRAFT: 'Draft',
            PENDING: 'Pending',
            INPROGRESS: 'In Progress',
            COMPLETED: 'Completed',
            CANCEL: 'Cancel',
            ACHIEVED: 'Achieved'
        }
    },
    PROFILE: {
        PROFILESKILLS:{
          COMBOLABEL : 'Skill',
          RATINGLABEL : 'Rating'
        },
       EDUCATION: {
          TITLE : 'Education',
          ADDEDUCATION :'Add Education',
          EMPTYTEXT :  '<div class="ddo-emptytext">No Records Added</div>',
          PROVIDESCHOOL : 'Please provide your School/College Details',
          COURSE : 'Course',
          STARTYEAR : 'Start Year',
          ENDYEAR : 'End Year',
          SAVE : 'Save',
          CANCEL : 'Cancel'
        },
        SUMMARY : {
       EMPTYTEXT : '<div class="ddo-pro-summary-empty-text">No Projects Found</div>'
        },
        ROLESANDRESPONSIBILITIES : {
    EMPTYTEXT : '<div class="ddo-pro-summary-empty-text">No Roles And Responsibilities</div>'
        },
        APPACCESS : {
    EMPTYTEXT : '<div class="ddo-pro-summary-empty-text">No Apps/Subscriptions Found</div>'
        },
       INTERTESTS: {
         EMPTYTEXT : 'Add Your Interest',
         NOADDED : '<div class = "ddo-emptytext">No Interests Added</div>'
        },
        ADDJOB : {
         EXPERIENCE : 'Experience',
         ADD : 'Add Job',
         DESIGNATION : 'Designation',
         COMPANY : 'Company',
         LOCATION : 'Location',
         TIMEPERIOD : 'Time Period',
         MONTH : 'Month',
         YEAR : 'Year',
         MANDATORY:"This is mandatory",
         TO :'To',
         CURRENTWORK : 'I Currently Work Here',
         DESCRIPTION : 'Description',
         SAVE :'Save',
         CANCEL : 'Cancel',
         EMPTYTEXT : '<div class="ddo-emptytext">No Jobs Added</div>'
        },
        REPORTING : {
        EMPTYTEXT : '<div class="ddo-emptytext" >No data found</div>',
        CHANGEDBY  : 'Changed By',
        REPORTINGMANAGER : 'Reporting Manager',
        FRMDATE : 'From Date',
        TODATE : 'To Date'
        },
        ADDEDUCATION :{
        SAVE : 'Save',
       EMPTYCOURSE : 'Course'
        },
        NOMINATE: 'Nominate',
        ALLOCATION: 'Project Summary',
        EDITPERSONAL: 'Edit Personel Details',
        PROJECTHISTORY: 'Project History',
        REPORTINGMNGRHISTORY: 'Reporting Manager History',
        VIEWTIMELINE: 'View Timeline',
        ACTIVITY: 'Activity',
        FEEDBACK: 'Feedback',
        COMMENTS: 'Comments - Minimum 140 Characters',
        SUBMIT: 'Submit',
        NODATA: '<div class="ddo-emptytext" >No data found</div>',
        MONTH: 'Month',
        POINTS: 'Points',
        DESCRIPTION: 'Description',
        BYTO: 'By/To',
        TRXTYPE: 'trxtype',
        BY: 'By',
        NOSKILL: '<div class="ddo-emptytext">No Skills Added</div>',
        SKILLS: 'Skills',
        ADDSKILLS: 'Add Skills',
        OK: 'Ok',
        CANCEL: 'Cancel',
        REASON: 'Reason',
        WRITESOMETHING: 'Write something...',
        PERSONALDETAILS: {
            SAVE: 'Save',
            CANCEL: 'Cancel',
            FIRSTNAME: 'First Name',
            MIDDLENAME: 'Middle Name',
            LASTNAME: 'Last Name',
            EMAIL: 'Email',
            EMPCODE: 'Employee Code',
            PANNUMBER: 'PAN Number',
            ADDRESS: 'Address',
            DOB: 'Date Of Birth',
            DATEEMPTYTEXT: 'DD-MM-YYYY',
            GENDER: 'Gender',
            MALE: 'Male',
            FEMALE: 'Female',
            MARITALSTATUS: 'Marital Status',
            ANNIVERSARYDATE: 'Anniversary Date',
            PHONEEMPTY: 'Enter phone number',
            PHONEREGEX: 'Enter Valid phone number ex: 9848012345',
            PHONELABEL: 'Phone number',
            EMERGENCYPHN: 'Emergency Number',
            BLOODGROUP: 'Blood Group',
            PANNO: 'Pan No',
            ADHAARNO: 'Aadhar No',
            CADDRESS: 'Current Address',
            DETAILS: 'Details',
            COUNTRY: 'Country',
            STATE: 'State',
            CITY: 'City',
            ZIP: 'Zip Code',
            PADDRESS: 'Permanent Address',
            CHECKADDRESS: 'Check if CurrentAddress and PermanentAddress are same.',
        
        }
    },
    HOME: {
        TOP: 'TOP',
        KARMASCORE: {
            VIEWALL: 'View all',
            SHOWDETAILS: 'Show Details',
            NOUSERFOUND: '<div class="karma-empty-employee">No User Found !!!</div><div class="karma-emptyicon-cls"></div>',
            NODATAFOUND: '<div class="ddo-karma-search-empty">No Data Found</div>',
            ADDTASK: 'Add Task'
        },
        TODO: {
            ENJOYDAY: '<div class="todo-empty">Enjoy the day <br><br> <img class="ddo-todo-emptyImage" src="resources/images/todo/todoEmpty.png"></div>',
            TASK: 'Task',
            EDIT: 'Edit',
            DELETE: 'Delete',
            TODOLIST: 'ToDo List',
            SEARCHTODOTASK: 'Search Todo Task',
            PENDING: 'Pending',
            COMPLETED: 'Completed',
            ADDTASK: 'Add Task',
            UNDOTASK: 'Undo the Task Completion',
            TASKDETAILS: 'Todo Task Details',
            OK: 'Ok',
            CANCEL: 'Cancel'
        },
        FEEDS: {
            LOADING: 'Loading...',
            NOFEED: '<img src="resources/images/feeds/nofeeds.png" class="nofeeds-cls">',
            CLOSE: 'Close',
            NOLIKE: '<div class="no-likes-cls">No likes found!</div>',
            ATTACHFILE: 'Attach File',
            SHAREABLE: 'Shareable',
            POST: 'Post',
            NOSHAREDATA: 'No data available',
            TAGPEOPLEGROUP: 'Tag People or Groups',
            CLEARFILTER: 'Clear Filters',
            NOFILTERDATA: 'No data available',
            ADDFILTER: "Add Filter",
            AUTHOR: 'Author',
            AUTHORNAME: 'Name',
            DATERANGE: 'Date Range',
            SELECTRANGE: 'Select Range',
            POSTTYPE: 'Post Type',
            UPDATE: 'Update',
            IDEATE: 'Ideate',
            BOTH: 'Both',
            APPLY : 'Apply',
        }
    },
    VIEWPORT:{
        NOMINATE: 'Nominate',
        NOMINATEOTHER: 'Nominate Colleagues',
        SELFNOMINATE: 'Self Nominate',
        REDEEM: 'Redeem',
        USERIMAGE:'Current user image',
        PROFILE:'Profile',
        LOGOUT: 'Logout',
        LOCATION: 'Location',
    }
});

// LabelsTitles.HOME.FEEDS.Apply